### PR TITLE
resume upload methods

### PR DESCRIPTION
**Pull request by Jan-E**
See https://github.com/NMSSH/NMSSH/issues/176

### CODE REVIEW

**Comment by Jan-E** [comment]
This PR introduces resumeFileAtPath:toFileAtPath:

resumeFileAtPath:toFileAtPath: is completely comparable with writeFileAtPath:toFileAtPath:
http://cocoadocs.org/docsets/NMSSH/2.2.5/Classes/NMSFTP.html#//api/name/writeFileAtPath:toFileAtPath:

The differences:

1. resumeFileAtPath does not overwrite the destination file, but looks if the destination file exists. If it exists it appends the part of the inputfile that has not been uploaded yet to the end of the destination file.
2. resumeFileAtPath has a progress method that returns 2 integers: the first is the number of bytes appended in the current call and the second is the number of bytes in total (= the current filesize of the output file)

I am now using resumeFileAtPath as follows:
```
success = [self.uploadSession.sftp
    resumeFileAtPath:localFile
    toFileAtPath:destFile
    progress:^(NSUInteger delta, NSUInteger totalBytes) {
// do stuff with success, delta and totalBytes here
}
```

**Comment by Jan-E** [comment]
Additional Instance methods added:

resumeStream:toFileAtPath:progress: = the resume version of writeStream:toFileAtPath:progress:
This one also returns 2 integers in the progress method

resumeStream:toSFTPHandle:progress:
This is internal only and cannot be called directly.
Note: I did not add this to the @interface NMSFTP in the head of NMSFTP.m yet. If needed I can of course do such.

**Comment by Jan-E** [comment]
Implementation details.

My first proposal was at https://github.com/NMSSH/NMSSH/issues/176 but that proposal was only returning the number of bytes appended in the current call. So I had to keep track of the number of bytes appended in every call to resumeFileAtPath to know how far from the end I was.

@Frugghi suggested a way to return 2 integers here: https://github.com/NMSSH/NMSSH/issues/176#issuecomment-213744309 I tried to implement that, but ran into problems because my first patch did a final call to writeStream:toSFTPHandle:progress: with only 1 integer in progress:(BOOL (^)(NSUInteger))progress from a method with 2 integers in the progress method.

To overcome this I added resumeStream:toSFTPHandle:progress with 2 integers as well. This is the order of calling now:

resumeFileAtPath:toFileAtPath: to
resumeStream:toFileAtPath:progress: to
resumeStream:toSFTPHandle:progress

All three instance methods share the same progress:(BOOL (^)(NSUInteger delta, NSUInteger totalBytes))progress. at the end of the chain these integers are calculated as follows:
https://github.com/Jan-E/NMSSH/blob/resume/NMSSH/NMSFTP.m#L382

`
                if (progress && !progress(delta, delta + (NSUInteger)attributes.filesize))
`

The change of offsets is done in line line 364 up until line 367:
https://github.com/Jan-E/NMSSH/blob/resume/NMSSH/NMSFTP.m#L364

```
    libssh2_sftp_seek64(handle, attributes.filesize);
    NMSSHLogVerbose(@"Seek to position %llu of destFile", attributes.filesize);
    
    [inputStream setProperty:[NSNumber numberWithUnsignedLongLong:attributes.filesize] forKey:NSStreamFileCurrentOffsetKey];

```

**Comment by Jan-E** [comment]
@Lejdborg @Frugghi Please review this PR and merge it if it seems fit to you.

**Comment by Frugghi** [comment]
Seems fine to me.

**Comment by Jan-E** [comment]
Great!

**Pull request merged**
